"""precio como float

Revision ID: 3744e7f89858
Revises: cc8f364d5c43
Create Date: 2026-01-18 22:46:39.386118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3744e7f89858'
down_revision: Union[str, Sequence[str], None] = 'cc8f364d5c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tour', 'precio',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('tour', 'politicas',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('zarpe', sa.Column('detalles', sa.JSON(), nullable=True))
    op.alter_column('zarpe', 'id_tour',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('zarpe', 'observaciones',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('zarpe', 'id_usuario_created',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('zarpe_id_operadora_fkey'), 'zarpe', type_='foreignkey')
    op.drop_constraint(op.f('zarpe_id_reserva_fkey'), 'zarpe', type_='foreignkey')
    op.drop_column('zarpe', 'id_reserva')
    op.drop_column('zarpe', 'hora_llegada')
    op.drop_column('zarpe', 'hora_salida')
    op.drop_column('zarpe', 'id_operadora')
    op.drop_column('zarpe', 'nombre_guia')
    op.drop_column('zarpe', 'pasajeros')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zarpe', sa.Column('pasajeros', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('zarpe', sa.Column('nombre_guia', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('zarpe', sa.Column('id_operadora', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('zarpe', sa.Column('hora_salida', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('zarpe', sa.Column('hora_llegada', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('zarpe', sa.Column('id_reserva', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('zarpe_id_reserva_fkey'), 'zarpe', 'reservas', ['id_reserva'], ['id'])
    op.create_foreign_key(op.f('zarpe_id_operadora_fkey'), 'zarpe', 'operadora', ['id_operadora'], ['id'])
    op.alter_column('zarpe', 'id_usuario_created',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('zarpe', 'observaciones',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('zarpe', 'id_tour',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('zarpe', 'detalles')
    op.alter_column('tour', 'politicas',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tour', 'precio',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
