"""Add checkout_session_id to Reservas

Revision ID: 3fc4a25bde8e
Revises: 941fa8a19011
Create Date: 2026-01-20 18:59:05.311107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3fc4a25bde8e'
down_revision: Union[str, Sequence[str], None] = '941fa8a19011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('checkout_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_reservas_checkout_session_id'), 'reservas', ['checkout_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_checkout_session_id'), table_name='reservas')
    op.drop_column('reservas', 'checkout_session_id')
    # ### end Alembic commands ###
