"""add payment_intent_id to reservas

Revision ID: 941fa8a19011
Revises: f0b37d2b3940
Create Date: 2026-01-19 23:18:09.581974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '941fa8a19011'
down_revision: Union[str, Sequence[str], None] = 'f0b37d2b3940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_reservas_payment_intent_id'), 'reservas', ['payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_payment_intent_id'), table_name='reservas')
    op.drop_column('reservas', 'payment_intent_id')
    # ### end Alembic commands ###
